apiVersion: v1
kind: Service
metadata:
  name: myonlineapp-svc
  labels:
     app: myonlineapp
     version: 2.7.2
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
      app: myonlineapp
      version: 2.7.2
  